// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpe8KiLwDvjSPXuOTtBpNqkK-tKGw8Y1M',
    appId: '1:22154943236:web:ee53d2d0bb506ed3364e51',
    messagingSenderId: '22154943236',
    projectId: 'gobox-8ffa8',
    authDomain: 'gobox-8ffa8.firebaseapp.com',
    storageBucket: 'gobox-8ffa8.firebasestorage.app',
    measurementId: 'G-5PD0NDJ7LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-VYxw1uP-VLbagkvB9EQ1VLBlxtwJ2U',
    appId: '1:22154943236:android:e5a3d47ac5740273364e51',
    messagingSenderId: '22154943236',
    projectId: 'gobox-8ffa8',
    storageBucket: 'gobox-8ffa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqA8xZkQhMfCp7-nwSZfEgok71iU7dj3s',
    appId: '1:22154943236:ios:5a56dffed6500328364e51',
    messagingSenderId: '22154943236',
    projectId: 'gobox-8ffa8',
    storageBucket: 'gobox-8ffa8.firebasestorage.app',
    iosBundleId: 'com.example.frontendGobox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqA8xZkQhMfCp7-nwSZfEgok71iU7dj3s',
    appId: '1:22154943236:ios:5a56dffed6500328364e51',
    messagingSenderId: '22154943236',
    projectId: 'gobox-8ffa8',
    storageBucket: 'gobox-8ffa8.firebasestorage.app',
    iosBundleId: 'com.example.frontendGobox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpe8KiLwDvjSPXuOTtBpNqkK-tKGw8Y1M',
    appId: '1:22154943236:web:a6dc4b16b7285b3d364e51',
    messagingSenderId: '22154943236',
    projectId: 'gobox-8ffa8',
    authDomain: 'gobox-8ffa8.firebaseapp.com',
    storageBucket: 'gobox-8ffa8.firebasestorage.app',
    measurementId: 'G-L0ZTXGD71C',
  );
}
